### ISSUE TITLE
Meal app Raghav 12103490 

### ISSUE THREAD

**Issue by raghavprajapat2023** [ItsAdityaKSingh/git_project#42]
Name: Raghav 
Reg: 12103490 
Roll: R9541KA07

![348556140-c49c1153-b278-4867-9c5e-c1e25a8c1eb4](https://github.com/user-attachments/assets/6b92de58-06d9-4801-864f-8d5c1810f116)

**Comment by ItsAdityaKSingh** [comment]
Bro you had to make a PR, not raise an issue :|
